In [62]:
import polars as pl

In [63]:
# Use Polars to read the Parquet file lazily
df = pl.scan_parquet('C:/Users/ayo/Downloads/CRS-parquet (1)/CRS.parquet')
# Collect to get a DataFrame and print column names
schema = df.collect().columns
print(schema)

['year', 'donor_code', 'de_donorcode', 'donor_name', 'agency_code', 'agency_name', 'crs_id', 'project_number', 'initial_report', 'recipient_code', 'de_recipientcode', 'recipient_name', 'region_code', 'de_regioncode', 'region_name', 'incomegroup_code', 'de_incomegroupcode', 'incomegroup_name', 'flow_code', 'flow_name', 'bi_multi', 'category', 'finance_t', 'aid_t', 'usd_commitment', 'usd_disbursement', 'usd_received', 'usd_commitment_defl', 'usd_disbursement_defl', 'usd_received_defl', 'usd_adjustment', 'usd_adjustment_defl', 'usd_amount_untied', 'usd_amount_partial_tied', 'usd_amount_tied', 'usd_amount_untied_defl', 'usd_amount_partial_tied_defl', 'usd_amounttied_defl', 'usd_irtc', 'usd_expert_commitment', 'usd_expert_extended', 'usd_export_credit', 'currency_code', 'commitment_national', 'disbursement_national', 'grant_equiv', 'usd_grant_equiv', 'usd_grant_equiv_defl', 'short_description', 'project_title', 'purpose_code', 'purpose_name', 'sector_code', 'sector_name', 'channel_code', 'channel_name', 'channel_reported_name', 'parent_channel_code', 'geography', 'ld_cflag', 'ld_cflag_name', 'expected_start_date', 'completion_date', 'long_description', 'sd_gfocus', 'keywords', 'gender', 'environment', 'dig', 'trade', 'rmnch', 'drr', 'nutrition', 'disability', 'ftc', 'pba', 'investment_project', 'blended_finance_type', 'biodiversity', 'climate_mitigation', 'climate_adaptation', 'desertification', 'commitment_date', 'type_repayment', 'number_repayment', 'interest1', 'interest2', 'repaydate1', 'repaydate2', 'usd_interest', 'usd_outstanding', 'usd_arrears_principal', 'usd_arrears_interest', 'budget_ident', 'capital_expend', 'ps_iflag', 'ps_iflag_name', 'psi_add_type', 'psi_add_desc', 'psi_add_dev_obj', 'usd_psi_gr_eq_memo', 'usd_psi_gr_eq_memo_defl']

In [64]:
[col for col in schema if 'sector' in col]

['sector_code', 'sector_name']

In [65]:
df.select(['sector_code', 'sector_name']).describe()

shape: (9, 3)
┌────────────┬─────────────┬─────────────────────────────────┐
│ statistic  ┆ sector_code ┆ sector_name                     │
│ ---        ┆ ---         ┆ ---                             │
│ str        ┆ f64         ┆ str                             │
╞════════════╪═════════════╪═════════════════════════════════╡
│ count      ┆ 6.240806e6  ┆ 6240802                         │
│ null_count ┆ 6934.0      ┆ 6938                            │
│ mean       ┆ 320.076195  ┆ null                            │
│ std        ┆ 263.023707  ┆ null                            │
│ min        ┆ 100.0       ┆ Administrative Costs of Donors  │
│ 25%        ┆ 140.0       ┆ null                            │
│ 50%        ┆ 210.0       ┆ null                            │
│ 75%        ┆ 410.0       ┆ null                            │
│ max        ┆ 998.0       ┆ VIII.3. Disaster Prevention & … │
└────────────┴─────────────┴─────────────────────────────────┘

In [66]:
df.select(['sector_name']).unique().sort('sector_name').collect()['sector_name'].to_list()

[None,
 'Administrative Costs of Donors',
 'I. Social Infrastructure & Services',
 'I.1. Education',
 'I.1.a. Education, Level Unspecified',
 'I.1.b. Basic Education',
 'I.1.c. Secondary Education',
 'I.1.d. Post-Secondary Education',
 'I.2. Health',
 'I.2.a. Health, General',
 'I.2.b. Basic Health',
 'I.2.c. Non-communicable diseases (NCDs)',
 'I.3. Population Policies/Programmes & Reproductive Health',
 'I.4. Water Supply & Sanitation',
 'I.5. Government & Civil Society',
 'I.5.a. Government & Civil Society-general',
 'I.5.b. Conflict, Peace & Security',
 'I.6. Other Social Infrastructure & Services',
 'II. Economic Infrastructure & Services',
 'II.1. Transport & Storage',
 'II.2. Communications',
 'II.3. Energy',
 'II.3.a. Energy Policy',
 'II.3.b. Energy generation, renewable sources',
 'II.3.c. Energy generation, non-renewable sources',
 'II.3.d. Hybrid energy plants',
 'II.3.e. Nuclear energy plants',
 'II.3.f. Energy distribution',
 'II.4. Banking & Financial Services',
 'II.5. Business & Other Services',
 'III. Production Sectors',
 'III.1. Agriculture, Forestry, Fishing',
 'III.1.a. Agriculture',
 'III.1.b. Forestry',
 'III.1.c. Fishing',
 'III.2. Industry, Mining, Construction',
 'III.2.a. Industry',
 'III.2.b. Mineral Resources & Mining',
 'III.2.c. Construction',
 'III.3.a. Trade Policies & Regulations',
 'III.3.b. Tourism',
 'IV. Multi-Sector / Cross-Cutting',
 'IV.1. General Environment Protection',
 'IV.2. Other Multisector',
 'IX. Unallocated / Unspecified',
 'Refugees in Donor Countries',
 'Sectors not specified',
 'VI. Commodity Aid / General Programme Assistance',
 'VI.1. General Budget Support',
 'VI.2. Development Food Assistance',
 'VI.3. Other Commodity Assistance',
 'VII. Action Relating to Debt',
 'VIII. Humanitarian Aid',
 'VIII.1. Emergency Response',
 'VIII.2. Reconstruction Relief & Rehabilitation',
 'VIII.3. Disaster Prevention & Preparedness']

In [67]:
agric_crs = df.filter(pl.col('sector_name').str.contains('Agriculture', literal=True))

In [68]:
df.select('sector_name').collect().shape[0]

6247740

In [69]:
agric_crs.select('sector_name').collect().shape[0]

410597

In [70]:
keeplist=list(set(['year','donor_code','donor_name','agency_name', 'crs_id', 'project_number',
          'initial_report','recipient_code','de_recipientcode','recipient_name','region_code',
 'de_regioncode','initial_report','region_name', 'incomegroup_name', 'flow_code',
          'flow_name','bi_multi', 'category', 'finance_t', 'aid_t', 'usd_commitment', 'usd_disbursement',
           'usd_commitment_defl', 'usd_disbursement_defl','commitment_date','expected_start_date',
 'completion_date', 'long_description','keywords',  'channel_code','channel_name','channel_reported_name','parent_channel_code','geography','ld_cflag',
 'ld_cflag_name','sector_name','recipient_code',
 'de_recipientcode',
 'recipient_name',
 'region_code',
 'de_regioncode','short_description',
 'project_title',
 'purpose_code',
 'purpose_name','short_description',
 'project_title',
 'purpose_code',
 'long_description',]))

In [71]:
agric_crs.columns

C:\Users\ayo\AppData\Local\Temp\ipykernel_11636\2280205937.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  agric_crs.columns

['year',
 'donor_code',
 'de_donorcode',
 'donor_name',
 'agency_code',
 'agency_name',
 'crs_id',
 'project_number',
 'initial_report',
 'recipient_code',
 'de_recipientcode',
 'recipient_name',
 'region_code',
 'de_regioncode',
 'region_name',
 'incomegroup_code',
 'de_incomegroupcode',
 'incomegroup_name',
 'flow_code',
 'flow_name',
 'bi_multi',
 'category',
 'finance_t',
 'aid_t',
 'usd_commitment',
 'usd_disbursement',
 'usd_received',
 'usd_commitment_defl',
 'usd_disbursement_defl',
 'usd_received_defl',
 'usd_adjustment',
 'usd_adjustment_defl',
 'usd_amount_untied',
 'usd_amount_partial_tied',
 'usd_amount_tied',
 'usd_amount_untied_defl',
 'usd_amount_partial_tied_defl',
 'usd_amounttied_defl',
 'usd_irtc',
 'usd_expert_commitment',
 'usd_expert_extended',
 'usd_export_credit',
 'currency_code',
 'commitment_national',
 'disbursement_national',
 'grant_equiv',
 'usd_grant_equiv',
 'usd_grant_equiv_defl',
 'short_description',
 'project_title',
 'purpose_code',
 'purpose_name',
 'sector_code',
 'sector_name',
 'channel_code',
 'channel_name',
 'channel_reported_name',
 'parent_channel_code',
 'geography',
 'ld_cflag',
 'ld_cflag_name',
 'expected_start_date',
 'completion_date',
 'long_description',
 'sd_gfocus',
 'keywords',
 'gender',
 'environment',
 'dig',
 'trade',
 'rmnch',
 'drr',
 'nutrition',
 'disability',
 'ftc',
 'pba',
 'investment_project',
 'blended_finance_type',
 'biodiversity',
 'climate_mitigation',
 'climate_adaptation',
 'desertification',
 'commitment_date',
 'type_repayment',
 'number_repayment',
 'interest1',
 'interest2',
 'repaydate1',
 'repaydate2',
 'usd_interest',
 'usd_outstanding',
 'usd_arrears_principal',
 'usd_arrears_interest',
 'budget_ident',
 'capital_expend',
 'ps_iflag',
 'ps_iflag_name',
 'psi_add_type',
 'psi_add_desc',
 'psi_add_dev_obj',
 'usd_psi_gr_eq_memo',
 'usd_psi_gr_eq_memo_defl']

In [72]:
agric_crs.describe()

shape: (9, 103)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ year      ┆ donor_cod ┆ de_donorc ┆ … ┆ psi_add_d ┆ psi_add_d ┆ usd_psi_g ┆ usd_psi_ │
│ ---       ┆ ---       ┆ e         ┆ ode       ┆   ┆ esc       ┆ ev_obj    ┆ r_eq_memo ┆ gr_eq_me │
│ str       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ mo_defl  │
│           ┆           ┆ f64       ┆ str       ┆   ┆ str       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 410597.0  ┆ 410597.0  ┆ 410597    ┆ … ┆ 1163      ┆ 1296      ┆ 225.0     ┆ 225.0    │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 409434    ┆ 409301    ┆ 410372.0  ┆ 410372.0 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 2012.3708 ┆ 499.78606 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.428784  ┆ 0.441632 │
│           ┆ 48        ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 9.591872  ┆ 440.73126 ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.286341  ┆ 2.409051 │
│           ┆           ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1973.0    ┆ 1.0       ┆ 1UN002    ┆ … ┆ #N/A      ┆ #N/A      ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 2007.0    ┆ 11.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 2014.0    ┆ 302.0     ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 2020.0    ┆ 905.0     ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.045822  ┆ 0.045822 │
│ max       ┆ 2024.0    ┆ 1650.0    ┆ USA       ┆ … ┆ the Fund  ┆ to        ┆ 30.191806 ┆ 32.15682 │
│           ┆           ┆           ┆           ┆   ┆ provides  ┆ support   ┆           ┆ 3        │
│           ┆           ┆           ┆           ┆   ┆ long-term ┆ the achie ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ lo…       ┆ vement of ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [73]:
slim_agric_crs_df = agric_crs.select(keeplist)

In [74]:
slim_agric_crs_df.select(['finance_t']).unique().collect()['finance_t'].to_list()

[1102,
 423,
 432,
 310,
 4222,
 510,
 1100,
 421,
 424,
 433,
 425,
 520,
 210,
 422,
 110,
 1101,
 431]

In [75]:
agric_std_grants_df= slim_agric_crs_df.filter(pl.col('finance_t')==110)

In [76]:
agric_std_grants_df.select(['finance_t']).collect().shape

(299257, 1)

In [ ]:
#110 is code for standard grants
agric_std_grants_df.select(['finance_t']).collect().unique()

shape: (1, 1)
┌───────────┐
│ finance_t │
│ ---       │
│ i32       │
╞═══════════╡
│ 110       │
└───────────┘

In [ ]:
# 
agric_std_grants_df.select(['aid_t']).collect()['aid_t'].unique().to_list()

['C01',
 'B031',
 'E01',
 'B032',
 'E02',
 'B022',
 'B021',
 'D02',
 'B04',
 'H01',
 'D01',
 'B01',
 'G01',
 None,
 'B03',
 'B033',
 'A02']

In [ ]:
# 30 is code for private developmet finance
agric_private_dev_df=agric_std_grants_df.filter(pl.col('flow_code')==30)

In [80]:
agric_private_dev_df.select(pl.nth(0)).collect().shape

(15490, 1)

In [83]:
agric_private_dev_df.select(['initial_report']).collect()['initial_report'].value_counts()

shape: (3, 2)
┌────────────────┬───────┐
│ initial_report ┆ count │
│ ---            ┆ ---   │
│ i32            ┆ u32   │
╞════════════════╪═══════╡
│ 8              ┆ 1029  │
│ 1              ┆ 5222  │
│ 3              ┆ 9239  │
└────────────────┴───────┘

In [91]:
# group by year, initial_report, project_code and count rows
grouped = agric_private_dev_df.group_by(['year', 'project_number','initial_report']).agg(pl.len()).collect().sort(by=['year','project_number'])
print(grouped)

shape: (6_023, 4)
┌──────┬────────────────┬────────────────┬─────┐
│ year ┆ project_number ┆ initial_report ┆ len │
│ ---  ┆ ---            ┆ ---            ┆ --- │
│ i32  ┆ str            ┆ i32            ┆ u32 │
╞══════╪════════════════╪════════════════╪═════╡
│ 2009 ┆ OPP1001752     ┆ 1              ┆ 1   │
│ 2009 ┆ OPP1001841     ┆ 1              ┆ 1   │
│ 2009 ┆ OPP1001867     ┆ 1              ┆ 1   │
│ 2009 ┆ OPP1002076     ┆ 1              ┆ 1   │
│ 2009 ┆ OPP1002254     ┆ 1              ┆ 1   │
│ …    ┆ …              ┆ …              ┆ …   │
│ 2024 ┆ OPP1213393     ┆ 3              ┆ 8   │
│ 2024 ┆ OPP1215286     ┆ 3              ┆ 1   │
│ 2024 ┆ OPP1215550     ┆ 3              ┆ 1   │
│ 2024 ┆ OPP1215722     ┆ 3              ┆ 2   │
│ 2024 ┆ OZFN-24-005    ┆ 8              ┆ 1   │
└──────┴────────────────┴────────────────┴─────┘

In [92]:
agric_private_dev_df_with_commit= agric_private_dev_df.filter(pl.col('usd_commitment')>0)

In [95]:
agric_private_dev_df_with_commit.select(pl.nth(0)).collect().shape

(6625, 1)

In [ ]:
#we are  only concerned with rows where commitents are made or modified
agric_private_dev_df_with_commit.select(['initial_report']).collect()['initial_report'].value_counts()

shape: (3, 2)
┌────────────────┬───────┐
│ initial_report ┆ count │
│ ---            ┆ ---   │
│ i32            ┆ u32   │
╞════════════════╪═══════╡
│ 8              ┆ 1025  │
│ 3              ┆ 379   │
│ 1              ┆ 5221  │
└────────────────┴───────┘

In [98]:
final_csv=agric_private_dev_df_with_commit.collect()

In [99]:
# Save the filtered dataframe to a CSV file in the grants_data directory
import os
os.makedirs("../grants_data", exist_ok=True)
final_csv.write_csv("../grants_data/agric_private_dev_df_with_commit.csv")
print("Data written to ../grants_data/agric_private_dev_df_with_commit.csv")

Data written to ../grants_data/agric_private_dev_df_with_commit.csv